Update Traditional Chinese translation
WordlessEcho/Variable-Font-Test pull request #1
Opened 2023-09-11 02:40 UTC by abc0922001

2023-09-12 07:08 UTC, WordlessEcho commented on app/src/main/res/values-zh-rTW/values.xml
> +    <string name="project_homepage" translatable="false">
这个是`translatable="false"`，不用翻译的

2023-09-12 07:09 UTC, WordlessEcho commented on app/src/main/res/values-zh-rTW/values.xml
> +    <string name="feature_type_seek_bar">尋找條</string>
这个SeekBar就是上文的`滑動條`

2023-09-12 07:10 UTC, WordlessEcho commented on app/src/main/res/values-zh-rTW/values.xml
> +    <string name="feature_type_switch">切換</string>
这个是「开关」

2023-09-12 07:11 UTC, WordlessEcho requested changes
Part of tag adding needs to imporve

2023-09-12 07:18 UTC, WordlessEcho commented on app/src/main/res/values-zh-rTW/values.xml
> +    <string name="pref_category_variations">變化</string>
我看到有文章翻译为「字型變體」，您认为哪个更加合适？
[第五章：字型（10） - iT 邦幫忙::一起幫忙解決難題，拯救 IT 人的一天](https://ithelp.ithome.com.tw/articles/10227899)

2023-09-12 07:18 UTC, WordlessEcho commented on app/src/main/res/values-zh-rTW/values.xml
> +    <string name="add_font_variation">新增字型變化</string>
如上 https://github.com/WordlessEcho/Variable-Font-Test/pull/1/files#r1322558406

2023-09-12 07:28 UTC, WordlessEcho commented on app/src/main/res/values-zh-rTW/values.xml
> +    <string name="feature_chws">上下文半寬間距（chws）</string>
Contextual Half-width Spacing我个人的理解是「标点挤压」，但是标点挤压包含`chws`又不仅限于`chws`，所以我故意在简中翻译里打了括号标注`chws`
这是一个源于Adobe Illustrator的翻译名词，您可以按照[在 Illustrator 中設定東亞字元格式](https://helpx.adobe.com/tw/illustrator/using/formatting-asian-characters.html)翻译为「排字調整」
另可参见[The Type — 文字 / 设计 / 文化    » 挤进推出避头尾](https://www.thetype.com/2018/05/14501/#ProhibitRule-strict)

2023-09-12 07:49 UTC, WordlessEcho commented on app/src/main/res/values-zh-rTW/values.xml
> +    <string name="feature_chws">上下文半寬間距（chws）</string>
不如说是英文原文需要更正……有点复杂

2023-09-12 09:19 UTC, merged

2023-09-12 09:19 UTC, WordlessEcho commented
非常感谢您的贡献，一会就会推新版本

2023-09-12 11:30 UTC, WordlessEcho commented
Contextual Half-width Spacing翻译成「調整連續標點的排字間距」您看怎么样？

2023-09-13 01:55 UTC, abc0922001 commented
> Contextual Half-width Spacing翻译成「調整連續標點的排字間距」您看怎么样？

我覺得滿好的，很好地解釋 chws 的定義